#+STARTUP: overview
* Emacs
At this point I'm still using Doom Emacs for everyday use, but I'm beginning to
build a custom config. Once I'm ready to use this config I'll have to change the
file to =~/.emacs.d/init.el=.
** Instructions and Troubleshooting
1. Emacs has pretty good docs. There's also the Worg.
2. Use =M-x org-babel-tangle= to generate the config.
** Note to Self
I need to add this note to myself at the top of the config so that I remember to
edit this file instead of the config file.
#+BEGIN_SRC emacs-lisp :tangle ./init.el
;     ___           _ _
;    /   \___  _ __( ) |_
;   / /\ / _ \| '_ \/| __|
;  / /_// (_) | | | || |_
; /___,' \___/|_| |_| \__|
;
;           _ _ _
;   ___  __| (_) |_
;  / _ \/ _` | | __|
; |  __/ (_| | | |_
;  \___|\__,_|_|\__|
;
;      _ _               _   _
;   __| (_)_ __ ___  ___| |_| |_   _
;  / _` | | '__/ _ \/ __| __| | | | |
; | (_| | | | |  __/ (__| |_| | |_| |_
;  \__,_|_|_|  \___|\___|\__|_|\__, (_)
;                              |___/
;    __   _ _ _
;   /__\_| (_) |_
;  /_\/ _` | | __|
; //_| (_| | | |_
; \__/\__,_|_|\__|
;
;  _   _
; | |_| |__   ___
; | __| '_ \ / _ \
; | |_| | | |  __/
;  \__|_| |_|\___|
;
;    ___                                     _
;   /___\_ __ __ _       _ __ ___   ___   __| | ___
;  //  // '__/ _` |_____| '_ ` _ \ / _ \ / _` |/ _ \
; / \_//| | | (_| |_____| | | | | | (_) | (_| |  __/
; \___/ |_|  \__, |     |_| |_| |_|\___/ \__,_|\___|
;            |___/
;   __ _ _
;  / _(_) | ___
; | |_| | |/ _ \
; |  _| | |  __/_
; |_| |_|_|\___(_)
;
#+END_SRC
** User Interface Improvements
*** Add Padding From the Edge of the Screen
This adds some space between the edges of the screen and the buffer. (I think
it's the buffer, but I'm not sure. It could technically be the window.)
#+BEGIN_SRC emacs-lisp :tangle ./init.el
(set-fringe-mode 50)
#+END_SRC
*** No Tooltips
Tooltips are distracting.
#+BEGIN_SRC emacs-lisp :tangle ./init.el
(tooltip-mode -1)
#+END_SRC
*** No Tool Bar
None of those silly icons at the top of the frame.
#+BEGIN_SRC emacs-lisp :tangle ./init.el
(tool-bar-mode -1)
#+END_SRC
*** No Scroll Bar
Get rid of the scroll bar.
#+BEGIN_SRC emacs-lisp :tangle ./init.el
(scroll-bar-mode -1)
#+END_SRC
*** Use a Better Default Color Scheme
Use a dark default color scheme.
#+BEGIN_SRC emacs-lisp :tangle ./init.el
(load-theme 'tango-dark)
#+END_SRC
* Shell
This config should work for most shells. That being said, you'll have to change
each tangle header argument to specify the proper file. You could just do a
search and replace. See [[* Instructions and Troubleshooting][Instructions and Troubleshooting]] for more info. I
followed [[https://web.archive.org/web/20190924102437/https://expoundite.net/guides/dotfile-management][this tutorial]] to figure this out.
** Instructions and Troubleshooting
 1. As noted above, change the tangle header to specify the proper config file.
    A search and replace should be easy enough.
 2. To generate the config, enter =M-x org-babel-tangle=.
 3. Enter =source ~/.zshrc= (or =source ~/.bashrc=).
** Note to Self
I need to add this note to myself at the top of the config so that I remember to
edit this file instead of the config file.
#+BEGIN_SRC conf :tangle ~/.zshrc
#     ___           _ _
#    /   \___  _ __( ) |_
#   / /\ / _ \| '_ \/| __|
#  / /_// (_) | | | || |_
# /___,' \___/|_| |_| \__|
#
#           _ _ _
#   ___  __| (_) |_
#  / _ \/ _` | | __|
# |  __/ (_| | | |_
#  \___|\__,_|_|\__|
#
#      _ _               _   _
#   __| (_)_ __ ___  ___| |_| |_   _
#  / _` | | '__/ _ \/ __| __| | | | |
# | (_| | | | |  __/ (__| |_| | |_| |_
#  \__,_|_|_|  \___|\___|\__|_|\__, (_)
#                              |___/
#    __   _ _ _
#   /__\_| (_) |_
#  /_\/ _` | | __|
# //_| (_| | | |_
# \__/\__,_|_|\__|
#
#  _   _
# | |_| |__   ___
# | __| '_ \ / _ \
# | |_| | | |  __/
#  \__|_| |_|\___|
#
#    ___                                     _
#   /___\_ __ __ _       _ __ ___   ___   __| | ___
#  //  // '__/ _` |_____| '_ ` _ \ / _ \ / _` |/ _ \
# / \_//| | | (_| |_____| | | | | | (_) | (_| |  __/
# \___/ |_|  \__, |     |_| |_| |_|\___/ \__,_|\___|
#            |___/
#   __ _ _
#  / _(_) | ___
# | |_| | |/ _ \
# |  _| | |  __/_
# |_| |_|_|\___(_)
#
#+END_SRC
** Variables
Set up base directory variable in case I ever move the base directory.
#+BEGIN_SRC conf :tangle ~/.zshrc
BASE_DIR="~/base"
#+END_SRC
** Aliases
*** Auto-Generated
I have a script that prints a list of repos that I manually add to my config. I
won't write them here for privacy reasons. (Some of my repos are private.)
*** Common Commands
#+BEGIN_SRC conf :tangle ~/.zshrc
alias c="clear"
alias lazy="git commit -am \"Lazy update.\" && git push"
alias ll="ls -ahl"
alias q="exit"
#+END_SRC
*** Common Navigations
#+BEGIN_SRC conf :tangle ~/.zshrc
alias desk="cd ~/Desktop"
alias schl="cd ${BASE_DIR}/1-school"
alias phet="cd ${BASE_DIR}/2-work/phet/repos"
alias rose="cd ${BASE_DIR}/2-work/phet/repos/rosetta"
alias free="cd ${BASE_DIR}/3-free"
alias rscf="cd ~/.phet/ && vim rosetta-config.json"
alias ..="cd .."
#+END_SRC
*** SSH
#+BEGIN_SRC conf :tangle ~/.zshrc
alias elra="ssh limu0834@elra-02.cs.colorado.edu"
alias phdv="ssh limu0834@phet-server-dev.int.colorado.edu"
alias phsv="ssh limu0834@phet-server.int.colorado.edu"
#+END_SRC
*** VPN
#+BEGIN_SRC conf :tangle ~/.zshrc
alias cvpn='/opt/cisco/anyconnect/bin/vpn connect vpn.colorado.edu'
alias dvpn='/opt/cisco/anyconnect/bin/vpn disconnect'
alias svpn='/opt/cisco/anyconnect/bin/vpn status'
#+END_SRC
** Path
Modify the path variable so that stuff for MacPorts gets looked for first, then
Doom Emacs, then default, and finally my scripts. From what I understand,
MacPorts tries to be orthogonal from macOS.
+ MacPorts:
  - =/opt/local/bin:/opt/local/sbin:=
+ Doom Emacs on macOS:
  - =/Users/liam/.emacs.d/bin:=
  - =/Applications/MacPorts/Emacs.app/Contents/MacOS:=
+ Default:
  - =/usr/bin:/bin:/usr/sbin:/sbin:=
+ My Scripts:
  - =/Users/liam/bin:=
#+BEGIN_SRC conf :tangle ~/.zshrc
PATH="/opt/local/bin:/opt/local/sbin:/Users/liam/.emacs.d/bin:/Applications/MacPorts/Emacs.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin:/Users/liam/bin:"
#+END_SRC
** Editor
Set the default editor. See [[https://askubuntu.com/a/432530][this SO answer]] for more info.
#+BEGIN_SRC conf :tangle ~/.zshrc
EDITOR="/usr/bin/vim"
#+END_SRC
* Vim
My philosophy for this config is to keep Vim simple. I mostly use Emacs, so when
I use Vim I want to get in and out quickly without much fuss.
** Instructions and Troubleshooting
1. If there's anything you don't understand or don't remember, Vim has excellent
   help pages. (RTFM, obviously.)
2. To generate the config, enter =M-x org-babel-tangle=.
** Note to Self
I need to add this note to myself at the top of the config so that I remember to
edit this file instead of the config file.
#+BEGIN_SRC conf :tangle ~/.vimrc
"     ___           _ _
"    /   \___  _ __( ) |_
"   / /\ / _ \| '_ \/| __|
"  / /_// (_) | | | || |_
" /___,' \___/|_| |_| \__|
"
"           _ _ _
"   ___  __| (_) |_
"  / _ \/ _` | | __|
" |  __/ (_| | | |_
"  \___|\__,_|_|\__|
"
"      _ _               _   _
"   __| (_)_ __ ___  ___| |_| |_   _
"  / _` | | '__/ _ \/ __| __| | | | |
" | (_| | | | |  __/ (__| |_| | |_| |_
"  \__,_|_|_|  \___|\___|\__|_|\__, (_)
"                              |___/
"    __   _ _ _
"   /__\_| (_) |_
"  /_\/ _` | | __|
" //_| (_| | | |_
" \__/\__,_|_|\__|
"
"  _   _
" | |_| |__   ___
" | __| '_ \ / _ \
" | |_| | | |  __/
"  \__|_| |_|\___|
"
"    ___                                     _
"   /___\_ __ __ _       _ __ ___   ___   __| | ___
"  //  // '__/ _` |_____| '_ ` _ \ / _ \ / _` |/ _ \
" / \_//| | | (_| |_____| | | | | | (_) | (_| |  __/
" \___/ |_|  \__, |     |_| |_| |_|\___/ \__,_|\___|
"            |___/
"   __ _ _
"  / _(_) | ___
" | |_| | |/ _ \
" |  _| | |  __/_
" |_| |_|_|\___(_)
"
#+END_SRC
** User Interface Improvements
*** Color Scheme
I like the default desert color scheme.
#+BEGIN_SRC conf :tangle ~/.vimrc
colorscheme desert
#+END_SRC
*** Column at 80 Characters
This draws a column at 80 characters.
#+BEGIN_SRC conf :tangle ~/.vimrc
set colorcolumn=80
#+END_SRC
*** Cursor Line
Draws a big line that shows where your cursor is.
#+BEGIN_SRC conf :tangle ~/.vimrc
set cursorline
#+END_SRC
*** Line Numbers
This shows the actual line number and numbers relative to that line number.
Showing relative line numbers is useful for commands and navigating.
#+BEGIN_SRC conf :tangle ~/.vimrc
set number relativenumber
#+END_SRC
*** Show Column Number in Status Line
This shows the line number and the column number in the status line.
#+BEGIN_SRC conf :tangle ~/.vimrc
set ruler
#+END_SRC
*** Status Line
This sets a persistent status line at the bottom of the screen.
#+BEGIN_SRC conf :tangle ~/.vimrc
set laststatus=2
#+END_SRC
** Tools
*** Check Spelling
This turns spell check on by default. I think this is a good idea because I
often forget to check my spelling.
#+BEGIN_SRC conf :tangle ~/.vimrc
set spell
set spelllang=en_us
#+END_SRC
*** Command Completion Menu
This turns on a nifty menu that allows you to complete commands with the =tab=
key.
#+BEGIN_SRC conf :tangle ~/.vimrc
set wildmenu
#+END_SRC
*** Highlight Search Items
Applies a highlight to items that match your search query.
#+BEGIN_SRC conf :tangle ~/.vimrc
set hlsearch
#+END_SRC
*** Syntax Highlighting
We always want syntax highlighting.
#+BEGIN_SRC conf :tangle ~/.vimrc
syntax enable
#+END_SRC
